apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
  namespace: wisecow
spec:
  type: NodePort
  ports:
    - port: 443
      targetPort: 4499
      nodePort: 30449
      protocol: TCP
  selector:
    app: wisecow

