name: Deploy Wisecow to Kubernetes

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: sand9162/wisecow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

      # ✅ Debug Kubernetes Configuration
      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > | base64 --decode >${Home}/.kube/config
          cat ${Home}/.kube/config|

      # ✅ Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          IMAGE_TAG=${{ github.sha }}
          kubectl apply -f k8s/deployment.yml -n wisecow
          kubectl apply -f k8s/service.yml -n wisecow
          kubectl set image deployment/wisecow-deployment wisecow=$IMAGE_NAME:$IMAGE_TAG -n wisecow
          kubectl rollout status deployment/wisecow-deployment -n wisecow

      # ✅ Verify deployment
      - name: Verify deployment
        run: |
          kubectl get pods -n wisecow


