name: Build and Deploy to Kind

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: wisecow
  CLUSTER_NAME: wisecow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # ✅ Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4

      # ✅ Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ✅ Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # ✅ Install kubectl and kind
      - name: Install Kind and kubectl
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      # ✅ Create Kind Cluster
      - name: Create Kind Cluster
        run: |
          kind create cluster --name ${{ env.CLUSTER_NAME }}

      # ✅ Deploy to Kind
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yml
          kubectl apply -f k8s/cluster-issuer.yml
          kubectl apply -f k8s/ingress.yml
          kubectl rollout status deployment/wisecow

      # ✅ Get Status
      - name: Get Status
        run: |
          kubectl get pods
          kubectl get svc
          kubectl get ingress
