name: Deploy Wisecow to Kubernetes

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: sand9162/wisecow:latest
  KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ✅ Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ✅ Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ✅ Step 4: Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE
          
      # ✅ Step 5: Set up Kubeconfig
      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config
          kubectl config view


      # ✅ Step 6: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yml -n wisecow
          kubectl apply -f k8s/service.yml -n wisecow
          kubectl rollout restart deployment wisecow -n wisecow

      # ✅ Step 7: Verify deployment
      - name: Verify deployment
        run: |
          kubectl get pods -n wisecow

