name: Deploy Wisecow to Kubernetes

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: sand9162/wisecow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ✅ Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ✅ Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ✅ Step 4: Build and push Docker image
      - name: Build and push Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

      # ✅ Step 5: Set up Kubeconfig (Fixing localhost error)
      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config
          kubectl config use-context kind-wisecow

      # ✅ Step 6: Deploy to Kubernetes (Error Handling Added)
      - name: Deploy to Kubernetes
        run: |
          IMAGE_TAG=${{ github.sha }}
          kubectl apply -f k8s/deployment.yml -n wisecow
          kubectl apply -f k8s/service.yml -n wisecow
          kubectl set image deployment/wisecow wisecow=$IMAGE_NAME:$IMAGE_TAG -n wisecow || exit 1
          kubectl rollout status deployment/wisecow -n wisecow || exit 1

      # ✅ Step 7: Verify Deployment (Improved Output)
      - name: Verify deployment
        run: |
          kubectl get pods -n wisecow
          kubectl describe deployment wisecow -n wisecow

